version: '3.8'

services:
  airweave:
    build:
      context: ./airweave
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AIRWEAVE_CLOUD_TOKEN=${AIRWEAVE_CLOUD_TOKEN}
      - VECTOR_STORE_URL=http://qdrant:6333
    depends_on:
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qdrant_data:
